spring:
  profiles.active: info,default,extensions,secrets
---
spring:
  profiles: default
  jpa.properties.hibernate.id.new_generator_mappings: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost/CFBroker?autoReconnect=true'
    username: root
    password:

  credhub:
    enable: false

com.swisscom.cloud.sb.broker.credhub:
  keyLength: LENGTH_2048
  commonName:
  organization: ServiceBroker
  organizationUnit: SB
  locality: Bern
  state: Bern
  country: CH
  duration: 365
  certificateAuthority: false
  certificateAuthorityCredential:
  selfSign: false

com.swisscom.cloud.sb.broker.bosh.credhub:
  enable: false
  keyLength: LENGTH_2048
  commonName:
  organization: ServiceBroker
  organizationUnit: SB
  locality: Bern
  state: Bern
  country: CH
  duration: 365
  certificateAuthority: false
  certificateAuthorityCredential:
  selfSign: false

management:
  metrics:
    export:
      influx:
        enabled: false
        uri: http://localhost:8086
        step: 5s
        userName:
        db: osb-metrics
        env: "local"
    enable:
      jvm: false
      dataSource: false
      tomcat: false
      process: false
      system: false
      http: false
      logback: false

endpoints:
  # accessibility of the endpoints is handled in ApplicationUserDetailsService class
  enabled: false
  # renaming of the spring boot actuator endpoint from info to version -> /info can only be accessed under /version
  info:
    enabled: true
    id: version

server.tomcat.accesslog.enabled: true

com.swisscom.cloud.sb.broker.security.platformUsers:
   - username: cc_admin
     password: change_me
     role: CF_ADMIN
     platformId: 00000000-0000-0000-0000-000000000000
   - username: cc_ext
     password: change_me
     role: CF_EXT_ADMIN
     platformId: 00000000-0000-0000-0000-000000000000

com.swisscom.cloud.sb.broker.backup:
  retryIntervalInSeconds: 10
  maxRetryDurationInMinutes: 30

com.swisscom.cloud.sb.broker.service.mariadb:
  nameOfDefault: "default"
  clusters:
  - name: "default"
    driver: com.mysql.cj.jdbc.Driver
    vendor: mysql
    host: 127.0.0.1
    port: 3306
    adminUser: 'root'
    adminPassword:
    databasePrefix: 'cfdb_'
    shieldAgentUrl: 'shield-agent:5444'
    discoveryURL: "http://localhost:8080/v2/api-docs"
    bindir: '/var/vcap/packages/shield-mysql/bin'

com.swisscom.cloud.sb.broker.shield:
  baseUrl: 'http://localhost:8082'
  apiKey: TEk22PhD6FeligOf3YvWyaAv
  agent: 'shield-agent:5444'
  jobPrefix: 'SB_CF_'
  targetPrefix: 'SB_CF_'
  storeName: 'local'
  retentionName: 'default'
  scheduleName: 'schedu'
  maxRetryBackup: 5
  defaultTenantName: tenant1
  username: admin
  password: shield

com.swisscom.cloud.sb.broker.service.openwhisk:
  openWhiskProtocol:
  openWhiskHost:
  openWhiskPath:
  openWhiskDbUser:
  openWhiskDbPass:
  openWhiskDbProtocol:
  openWhiskDbPort:
  openWhiskDbHost:
  openWhiskDbLocalUser:
  openWhiskDbHostname:

com.swisscom.cloud.sb.broker.service.mongodbent:
  opsManagerUrl: 'http://opsmanager.service.consul:8080'
  opsManagerUrlForAutomationAgent: '' #This parameter is optional
  opsManagerUser:
  opsManagerApiKey:
  portRange: '27000-40000'
  dbFolder: '/var/vcap/store/mongodb-data'
  libFolder: '/var/vcap/store/mongodb-mms-automation'
  logFolder: '/var/vcap/sys/log/mms-automation-agent'
  authSchemaVersion: 5
  mongoDbVersion: '3.4.3-ent'
  featureCompatibilityVersion: '3.4'
  configureDefaultBackupOptions: true
  snapshotIntervalHours: 6 #Supported values are 6, 8, 12, and 24
  snapshotRetentionDays: 3 # Supported values are 1 - 5
  dailySnapshotRetentionDays: 15 #Supported values are [3, 4, 5, 6, 7, 15, 30, 60, 90, 120, 180, 360]
  weeklySnapshotRetentionWeeks: 6 #Supported values are 1 - 52.
  monthlySnapshotRetentionMonths: 6 # Supported values are 1 - 36
  pointInTimeWindowHours: 24
  retryIntervalInSeconds: 15
  maxRetryDurationInMinutes: 30
  advancedBinding: true
  ipRanges: ['172.16.255.224/27']
  protocols: ['tcp'] # 'tcp,udp,icmp'
  boshDirectorBaseUrl: 'https://localhost:25556'
  boshDirectorUsername:
  boshDirectorPassword:
  openstackkUrl: 'https://localhost:5000/v2.0' #Optional config
  openstackUsername: #Optional config
  openstackPassword: #Optional config
  openstackTenantName: #Optional config
  boshManifestFolder: 'test/resources/bosh'

com.swisscom.cloud.sb.broker.service.kubernetes:
  kubernetesHost: "kubernetes-service-api.service.consul"
  kubernetesPort: "6443"
  kubernetesClientCertificate: |
  kubernetesClientKey: |

com.swisscom.cloud.sb.broker.service.kubernetes.redis.v1:
  kubernetesRedisHost: 'kubernetes-service-node.service.consul'
  retryIntervalInSeconds: 10
  maxRetryDurationInMinutes: 10
  discoveryURL: "http://localhost:8080/v2/api-docs"
  ipRanges: []
  protocols: [] # 'tcp,udp,icmp'
  redisConfigurationDefaults:
    MAX_CONNECTIONS: # Plan
    MAX_DATABASES: # Plan
    QUORUM: # Plan
    REDIS_SERVER_MAX_MEMORY: # Plan
    REDIS_MAX_MEMORY: # Plan
    REDIS_MAX_CPU: # Plan
    SENTINEL_MAX_CPU: # Plan
    SENTINEL_MAX_MEMORY: # Plan
    INFLUXDB_HOST: # Bosh
    INFLUXDB_PORT: 9086 # Bosh
    INFLUXDB_USER: admin # Bosh
    INFLUXDB_PASS: # Bosh
    ENVIRONMENT: # Deployment
    SHIELD_AUTHORIZED_KEYS: # Deployment

com.swisscom.cloud.sb.broker.service.servicebrokerserviceprovider:
  retryIntervalInSeconds: 5
  maxRetryDurationInMinutes: 600

com.swisscom.cloud.sb.broker.serviceDefinitions: [
  {
    "guid": "781e8f8c-c753-4a93-95eb-17c1f745b229",
    "name": "redisent",
    "description": "Redis Enterprise v3.2.3",
    "bindable": true,
    "asyncRequired": true,
    "internalName": "redisEnterprise",
    "displayIndex": 1,
    "metadata": {
      "version": "3.2.3",
      "displayName": "Redis Enterprise"
    },
    "plans": [
      {
        "guid": "ea4b1b7d-3060-4ac6-836b-e134de0e7d9b",
        "name": "large",
        "description": "Redis Sentinel Cluster with 3 data bearing nodes with 8 GB memory, 8 GB storage, unlimited concurrent connections",
        "templateId": "redisha-bosh-template-v2",
        "free": false,
        "displayIndex": 0,
        "containerParams": [
          {
            "template": "",
            "name": "plan",
            "value": "redis.large"
          },
          {
            "template": "",
            "name": "databases",
            "value": "32"
          },
          {
            "template": "",
            "name": "maxclients",
            "value": "60000"
          },
          {
            "template": "",
            "name": "vm_instance_type",
            "value": "redis.large"
          }
        ],
        "metadata": {
          "storageCapacity": "8GB",
          "memory": "8GB",
          "nodes": "3",
          "maximumConcurrentConnections": "unlimited",
          "dedicatedService": true,
          "highAvailability": true,
          "displayName": "large"
        }
      },
      {
        "guid": "ebe11e59-5261-4939-ac8f-0a35c3850b4e",
        "name": "xlarge",
        "description": "Redis Sentinel Cluster with 3 data bearing nodes with 16 GB memory, 16 GB storage, unlimited concurrent connections",
        "templateId": "redisha-bosh-template-v2",
        "free": false,
        "displayIndex": 1,
        "containerParams": [
          {
            "template": "",
            "name": "plan",
            "value": "redis.xlarge"
          },
          {
            "template": "",
            "name": "databases",
            "value": "32"
          },
          {
            "template": "",
            "name": "maxclients",
            "value": "60000"
          },
          {
            "template": "",
            "name": "vm_instance_type",
            "value": "redis.xlarge"
          }
        ],
        "metadata": {
          "storageCapacity": "16GB",
          "memory": "16GB",
          "nodes": "3",
          "maximumConcurrentConnections": "unlimited",
          "dedicatedService": true,
          "highAvailability": true,
          "displayName": "xlarge"
        }
      },
      {
        "guid": "7b71cf85-0e50-4509-af04-eafd3a6ad141",
        "name": "xxlarge",
        "description": "Redis Sentinel Cluster with 3 data bearing nodes with 32 GB memory, 32 GB storage, unlimited concurrent connections",
        "templateId": "redisha-bosh-template-v2",
        "free": false,
        "displayIndex": 2,
        "containerParams": [
          {
            "template": "",
            "name": "plan",
            "value": "redis.xxlarge"
          },
          {
            "template": "",
            "name": "databases",
            "value": "32"
          },
          {
            "template": "",
            "name": "maxclients",
            "value": "60000"
          },
          {
            "template": "",
            "name": "vm_instance_type",
            "value": "redis.xxlarge"
          }
        ],
        "metadata": {
          "storageCapacity": "32GB",
          "memory": "32GB",
          "nodes": "3",
          "maximumConcurrentConnections": "unlimited",
          "dedicatedService": true,
          "highAvailability": true,
          "displayName": "xxlarge"
        }
      }
    ],
    "tags": ["redis"]
  }
]

com.swisscom.cloud.sb.broker.serviceTemplates:
  - name: redis
    version: 1.0
    templates:
    - |
      apiVersion: v1
      kind: Namespace
      metadata:
        name:
    - |
      apiVersion: v1
      kind: Deployment
      metadata:
        name:
