spring:
  profiles.active: default,secrets
---
spring:
  profiles: default

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost/CFBroker?autoReconnect=true'
    username: root
    password:

endpoints:
  enabled: false
  info:
    enabled: true
    id: version

info:
  build:
    version: ${version}

com.swisscom.cloud.sb.broker:
  security:
    cfUsername: 'cc_admin'
    cfPassword: 'change_me'
    cfExtUsername: 'cf_ext'
    cfExtPassword: 'change_me'

  service:
    mongodbent:
      opsManagerUrl: 'http://localhost:55000'
      opsManagerUrlForAutomationAgent: '' #This parameter is optional
      opsManagerUser:
      opsManagerApiKey:
      portRange: '27000-40000'
      dbFolder: '/var/vcap/store/mongodb-data'
      libFolder: '/var/vcap/store/mongodb-mms-automation'
      logFolder: '/var/vcap/sys/log/mms-automation-agent'
      authSchemaVersion: 5
      mongoDbVersion: '3.2.6-ent'
      configureDefaultBackupOptions: true
      snapshotIntervalHours: 6 #Supported values are 6, 8, 12, and 24
      snapshotRetentionDays: 3 # Supported values are 1 - 5
      dailySnapshotRetentionDays: 10 #Supported values are 1 - 365
      weeklySnapshotRetentionWeeks: 6 #Supported values are 1 - 52.
      monthlySnapshotRetentionMonths: 6 # Supported values are 1 - 36
      pointInTimeWindowHours: 24
      retryIntervalInSeconds: 15
      maxRetryDurationInMinutes: 30
      advancedBinding: true
      ipRanges: ['172.16.255.224/27']
      protocols: ['tcp'] # 'tcp,udp,icmp'
      boshDirectorBaseUrl: 'https://localhost:25556'
      boshDirectorUsername:
      boshDirectorPassword:
      openstackkUrl: 'https://localhost:5000/v2.0' #Optional config
      openstackUsername: #Optional config
      openstackPassword: #Optional config
      openstackTenantName: #Optional config
      boshManifestFolder: 'test/resources/bosh'

  shield:
    baseUrl: 'https://shield.service.consul:8002'
    apiKey:
    agent: '10.244.2.2:5444'
    jobPrefix: 'SB_CF_'
    targetPrefix: 'SB_CF_'
    storeName: 'local'
    retentionName: 'default'
    scheduleName: 'schedu'

  backup:
    retryIntervalInSeconds: 10
    maxRetryDurationInMinutes: 30